# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

	config.vm.define "mongodb" do |mongodb|

		mongodb.vm.box = "ubuntu/trusty64"
		mongodb.vm.provision "shell", path: "mongodb/bootstrap.sh"
		mongodb.vm.provider "virtualbox" do |v|
			v.memory = 1024
			v.cpus = 1
		end

		config.vm.network "forwarded_port", guest: 27017, host: 27017
		config.vm.hostname = "mongodb.goldenlink.pl"

	end
end